package:
  name: komplexity
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: https://github.com/eclarke/komplexity.git

requirements:
  build:
    - rust

  run:
    - rust

test:
  commands:
    - kz -h

about:
  home: https://github.com/eclarke/komplexity

