package:
  name: komplexity
  version: "0.2.1" 

source:
  git_url: https://github.com/eclarke/komplexity.git

requirements:
  build:
    - rust # >1.21.0 #can be found in clinicalgraphics channel
    - cargo

  run:
    - rust

test:
  commands:
    - kz -h

about:
  home: https://github.com/eclarke/komplexity

